### ISSUE TITLE
cant install it no matter what

### ISSUE THREAD

**Issue by chiron852** [Its-Vichy/IOGen#24]
module hcaptcha not found pip install hcaptcha gives error

**Comment by Its-Vichy** [comment]
cuz you need to install from hcap github repo

**Comment by chiron852** [comment]
https://github.com/orgs/hCaptcha/repositories i just found this but idk how to install it

**Comment by Its-Vichy** [comment]
download file and include into project

**Comment by Marethyu9999** [comment]
`pip install -U git+https://github.com/h0nde/py-hcaptcha`
as mentioned in ./solver/README.md

**Comment by Its-Vichy** [comment]
yes

**Comment by chiron852** [comment]
how to install git in path

**Comment by Its-Vichy** [comment]
install from public installer and then add the the environement variables btw when you install git is already in vars ?

**Comment by chiron852** [comment]
Traceback (most recent call last):
  File "C:\Users\chiro\Downloads\IOGen-main\IOGen-main\main.py", line 5, in <module>
    from modules.captcha import CaptchaSolver
  File "C:\Users\chiro\Downloads\IOGen-main\IOGen-main\modules\captcha.py", line 5, in <module>
    import cv2, os, json, hcaptcha
  File "C:\Program Files\Python310\lib\site-packages\hcaptcha\__init__.py", line 2, in <module>
    from .challenges import Challenge
  File "C:\Program Files\Python310\lib\site-packages\hcaptcha\challenges.py", line 7, in <module>
    from .proofs import get_proof
  File "C:\Program Files\Python310\lib\site-packages\hcaptcha\proofs\__init__.py", line 2, in <module>
    from . import hsw
  File "C:\Program Files\Python310\lib\site-packages\hcaptcha\proofs\hsw.py", line 90, in <module>
    sio.connect("http://localhost:9932")
  File "C:\Program Files\Python310\lib\site-packages\socketio\client.py", line 331, in connect
    self.eio.connect(real_url, headers=real_headers,
  File "C:\Program Files\Python310\lib\site-packages\engineio\client.py", line 185, in connect
    return getattr(self, '_connect_' + self.transports[0])(
  File "C:\Program Files\Python310\lib\site-packages\engineio\client.py", line 324, in _connect_polling
    if self._connect_websocket(url, headers, engineio_path):
  File "C:\Program Files\Python310\lib\site-packages\engineio\client.py", line 421, in _connect_websocket
    except (ConnectionError, IOError, websocket.WebSocketException):
AttributeError: module 'websocket' has no attribute 'WebSocketException'

**Comment by chiron852** [comment]
if i use proxies will all these errors stop

**Comment by Its-Vichy** [comment]
wrong websocket library

**Comment by chiron852** [comment]
how do i fix

**Comment by PureAyGames** [comment]
> cuz you need to install from hcap github repo

has that python hcaptcha repo been deleted cuz when i clcik it or try to install its gone
![image](https://user-images.githubusercontent.com/74691018/162036171-f77f357e-31b7-474b-9606-0d82a75ad7ac.png)
![image](https://user-images.githubusercontent.com/74691018/162036265-6c55627d-1091-40b1-83ec-3be0cfee421d.png)
